/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progetto.Rooms;

import com.mycompany.progetto.ProjectObject;
import static com.mycompany.progetto.Commands.*;
import java.awt.event.WindowListener;
import javax.swing.Timer;
import static com.mycompany.progetto.Inventory.*;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author Utente
 */
public class Room0 extends javax.swing.JFrame {

    /**
     * Creates new form Room1
     */
    ProjectObject chiave, doorinizio;

    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {

            SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {

                @Override
                protected Void doInBackground() throws Exception {
                    this.publish("Dopo una serata di festeggiamenti ti ritrovi in questa casa sconosciuta");
                    Thread.sleep(3000);
                    this.publish("Il tuo nome è Bilbo Beggins e sei un Hobbit");
                    Thread.sleep(3000);
                    this.publish("Ieri sera hai parlato con Gandalf ma non ti ricordi quasi niente ");
                    Thread.sleep(3000);
                    this.publish("Ti ricordi solo che ti ha parlato di un anello");
                    Thread.sleep(3000);
                    this.publish("");
                    return null;
                }

                @Override
                protected void process(List<String> res) {
                    for (String thistext : res) {
                        text.setText(thistext);
                    }
                }

            };

            worker.execute();

        }

        @Override
        public void windowClosing(WindowEvent arg0) {

        }

        @Override
        public void windowClosed(WindowEvent arg0) {
        }

        @Override
        public void windowIconified(WindowEvent arg0) {

        }

        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }

        @Override
        public void windowActivated(WindowEvent arg0) {
        }

        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };

    public Room0() {
        initComponents();
        luogo.setText(" Stanza Principale");
        this.addWindowListener(l);
        chiave = new ProjectObject(0, "chiave");
        doorinizio = new ProjectObject(1, "door", "/images/iniziodoor.png", porta, this, 0, 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luogo = new javax.swing.JLabel();
        avanti = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        porta = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lo Hobbit");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("GIOCOMAP"); // NOI18N
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        luogo.setBackground(new java.awt.Color(0, 0, 0));
        luogo.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        luogo.setForeground(new java.awt.Color(255, 255, 255));
        luogo.setOpaque(true);
        luogo.setPreferredSize(new java.awt.Dimension(168, 168));
        getContentPane().add(luogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        avanti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHIUSO.png"))); // NOI18N
        avanti.setBorderPainted(false);
        avanti.setContentAreaFilled(false);
        avanti.setFocusPainted(false);
        avanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avantiActionPerformed(evt);
            }
        });
        getContentPane().add(avanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        inventario.setBorderPainted(false);
        inventario.setContentAreaFilled(false);
        inventario.setFocusPainted(false);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        porta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iniziodoor.png"))); // NOI18N
        porta.setToolTipText("door");
        porta.setBorderPainted(false);
        porta.setContentAreaFilled(false);
        porta.setFocusPainted(false);
        porta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portaActionPerformed(evt);
            }
        });
        getContentPane().add(porta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 150, 510));

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setFont(new java.awt.Font("Papyrus", 3, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setOpaque(true);
        text.setPreferredSize(new java.awt.Dimension(1080, 40));
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        sfondo.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/11.jpg"))); // NOI18N
        getContentPane().add(sfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avantiActionPerformed
        // TODO add your handling code here:
        goWest(this);
        //getThisGame().getmyRoom(0).getNorth().getThisRoom().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_avantiActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        // TODO add your handling code here:
        openInventory();
    }//GEN-LAST:event_inventarioActionPerformed

    private void portaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portaActionPerformed
        // TODO add your handling code here:
        if (findObject(chiave) >= 0 || doorinizio.isEnable() == 1) {

            if (findObject(chiave) >= 0) {
                doorinizio.setEnable(1);
                removeObject(chiave);
            }

            goEast(this);

        } else {
            text.setText("Non hai la chiave ");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }


    }//GEN-LAST:event_portaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton avanti;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel luogo;
    private javax.swing.JButton porta;
    public javax.swing.JLabel sfondo;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
