/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progetto.Rooms;

import static com.mycompany.progetto.Commands.openInventory;
import static com.mycompany.progetto.Commands.*;
import java.awt.event.WindowListener;
import javax.swing.Timer;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author MSIGaming
 */
public class Room15 extends javax.swing.JFrame {

    /**
     * Creates new form Room15
     */
    public Room15() {
        initComponents();
        luogo.setText("Gabbia Goblin");
        this.addWindowListener(l);
    }
    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {
            
            SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
                
                @Override
                protected Void doInBackground() throws Exception {
                    this.publish("ARGHHH...l'orco ti ha catturato...");
                    Thread.sleep(3000);
                    this.publish("Cerca di scappare,prima che ti utilizzi come spuntino!!!");
                    Thread.sleep(3000);
                    this.publish("");
                    return null;
                }
                
                @Override
                protected void process(List<String> res) {
                    for (String thistext : res) {
                        text.setText(thistext);
                    }
                }
                
            };
            
            worker.execute();
            
        }
        
        @Override
        public void windowClosing(WindowEvent arg0) {
            
        }
        
        @Override
        public void windowClosed(WindowEvent arg0) {
        }
        
        @Override
        public void windowIconified(WindowEvent arg0) {
            
        }
        
        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }
        
        @Override
        public void windowActivated(WindowEvent arg0) {
        }
        
        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        luogo = new javax.swing.JLabel();
        inventario = new javax.swing.JButton();
        paglia = new javax.swing.JButton();
        botola = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setFont(new java.awt.Font("Papyrus", 3, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setOpaque(true);
        text.setPreferredSize(new java.awt.Dimension(1080, 40));
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        luogo.setBackground(new java.awt.Color(0, 0, 0));
        luogo.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        luogo.setForeground(new java.awt.Color(255, 255, 255));
        luogo.setOpaque(true);
        getContentPane().add(luogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        inventario.setBorderPainted(false);
        inventario.setContentAreaFilled(false);
        inventario.setFocusPainted(false);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        paglia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paglia.png"))); // NOI18N
        paglia.setBorderPainted(false);
        paglia.setContentAreaFilled(false);
        paglia.setFocusPainted(false);
        paglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagliaActionPerformed(evt);
            }
        });
        getContentPane().add(paglia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 390, 190));

        botola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trap-door.png"))); // NOI18N
        botola.setBorderPainted(false);
        botola.setContentAreaFilled(false);
        botola.setFocusPainted(false);
        botola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botolaActionPerformed(evt);
            }
        });
        getContentPane().add(botola, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 330, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gabbia.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagliaActionPerformed
        paglia.setVisible(false);
        text.setText("Hai spostato la paglia");
        Timer timer = new Timer(4000, event -> {
            text.setText("");
        });
        timer.setRepeats(false);
        timer.start();
        
    }//GEN-LAST:event_pagliaActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        openInventory();        
    }//GEN-LAST:event_inventarioActionPerformed

    private void botolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botolaActionPerformed
        goNorth(this);
    }//GEN-LAST:event_botolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room15.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room15().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botola;
    private javax.swing.JButton inventario;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel luogo;
    private javax.swing.JButton paglia;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
