/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progetto;

import static com.mycompany.progetto.Commands.openInventory;
import static com.mycompany.progetto.Commands.*;
import java.awt.event.WindowListener;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.SwingWorker;

/**
 *
 * @author MSIGaming
 */
public class Room12 extends javax.swing.JFrame {
    
    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {
            
            SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {
                
                @Override
                protected Void doInBackground() throws Exception {
                    this.publish("ELROND:'Oh,era de secoli,anzi millenni che non si vedeva un hobbit qui!'");
                    Thread.sleep(4000);
                    this.publish("ELROND:'A cosa devo questa visita,mezz'uomo?");
                    Thread.sleep(4000);
                    this.publish("Mostri la mappa a Elrond");
                    Thread.sleep(4000);
                    this.publish("ELROND:'Le forze oscure stanno avanzando'");
                    Thread.sleep(3000);
                    this.publish("ELROND:'Questa mappa ti può condurre all'anello...'");
                    Thread.sleep(5000);
                    this.publish("ELROND:'Devi Proseguire a nord fino alle montagne nebbiose... '");
                    Thread.sleep(3000);
                    this.publish("ELROND:'La mappa porta fino a lì!'");
                    Thread.sleep(3000);
                    this.publish("ELROND:'Riprenditi la mappa,ti può tornare utile!'");
                    Thread.sleep(3000);
                    this.publish("Prendi la mappa");
                    Thread.sleep(3000);
                    this.publish("ELROND:'Prendi anche questo arco,giovane hobbit,potrà tornarti utile...");
                    Thread.sleep(3000);
                    this.publish("");
                    arco.setVisible(true);
                    nord.setVisible(true);
                    return null;
                }
                
                @Override
                protected void process(List<String> res) {
                    for (String thistext : res) {
                        text.setText(thistext);
                    }
                }
                
            };
            
            worker.execute();
            
        }
        
        @Override
        public void windowClosing(WindowEvent arg0) {
            
        }
        
        @Override
        public void windowClosed(WindowEvent arg0) {
        }
        
        @Override
        public void windowIconified(WindowEvent arg0) {
            
        }
        
        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }
        
        @Override
        public void windowActivated(WindowEvent arg0) {
        }
        
        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };
    
    ProjectObject bow;

    /**
     * Creates new form Room12
     */
    public Room12() {
        initComponents();
        this.addWindowListener(l);
        luogo.setText("Sala Elfica");
        bow = new ProjectObject(10, "arco elfico", "/images/legolas.png", arco, this);
        arco.setVisible(false);
        nord.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luogo = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        inventario = new javax.swing.JButton();
        nord = new javax.swing.JButton();
        arco = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        luogo.setBackground(new java.awt.Color(0, 0, 0));
        luogo.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        luogo.setForeground(new java.awt.Color(255, 255, 255));
        luogo.setOpaque(true);
        getContentPane().add(luogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setFont(new java.awt.Font("Papyrus", 3, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setOpaque(true);
        text.setPreferredSize(new java.awt.Dimension(1080, 40));
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, -1, -1));

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        inventario.setBorderPainted(false);
        inventario.setContentAreaFilled(false);
        inventario.setFocusPainted(false);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        nord.setFont(new java.awt.Font("Papyrus", 3, 18)); // NOI18N
        nord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NORD.png"))); // NOI18N
        nord.setBorderPainted(false);
        nord.setContentAreaFilled(false);
        nord.setFocusPainted(false);
        nord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nordActionPerformed(evt);
            }
        });
        getContentPane().add(nord, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        arco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/legolas.png"))); // NOI18N
        arco.setBorderPainted(false);
        arco.setContentAreaFilled(false);
        arco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcoActionPerformed(evt);
            }
        });
        getContentPane().add(arco, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elrond.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        openInventory();
    }//GEN-LAST:event_inventarioActionPerformed

    private void nordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nordActionPerformed
        goNorth(this);
    }//GEN-LAST:event_nordActionPerformed

    private void arcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcoActionPerformed
        // TODO add your handling code here:
        PickObject(bow);
    }//GEN-LAST:event_arcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arco;
    private javax.swing.JButton inventario;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel luogo;
    private javax.swing.JButton nord;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
