/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progetto;

import static com.mycompany.progetto.ProjectGameDescription.getInventory;

import static com.mycompany.progetto.ProjectGameDescription.getInventory;
import static com.mycompany.progetto.ProjectGameDescription.getRooms;
import static com.mycompany.progetto.Commands.*;
import java.awt.Image;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;
import static com.mycompany.progetto.Inventory.*;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingWorker;

/**
 *
 * @author MSIGaming
 */

public class Room6 extends javax.swing.JFrame {

    /**
     * Creates new form Room6
     */
    ProjectObject chiavetroll, spada;
    int kills = 0;
    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {

            SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {

                @Override
                protected Void doInBackground() throws Exception {
                    this.publish("BERTO: Sento puzza di Hobbit ");
                    Thread.sleep(3000);
                    this.publish("GUGLIELMO: E' il momento di mangiare");
                    Thread.sleep(3000);
                    this.publish("BERTO: Riscalda la pentola che si mangia ");
                    Thread.sleep(3000);
                    this.publish("Guarda,una chiave!");
                    Thread.sleep(3000);
                    this.publish("");
                    return null;
                }

                @Override
                protected void process(List<String> res) {
                    for (String thistext : res) {
                        text.setText(thistext);
                    }
                }

            };

            worker.execute();

        }

        @Override
        public void windowClosing(WindowEvent arg0) {

        }

        @Override
        public void windowClosed(WindowEvent arg0) {
        }

        @Override
        public void windowIconified(WindowEvent arg0) {

        }

        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }

        @Override
        public void windowActivated(WindowEvent arg0) {
        }

        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };

    public Room6() {
        initComponents();
        luogo.setText("Accampamento Troll");
        this.addWindowListener(l);
        morto.setVisible(false);
        teschio1.setVisible(false);
        teschio2.setVisible(false);
        chiavetroll = new ProjectObject(4, "chiave", "/images/trollkey.png", trollkey, this);
        spada = new ProjectObject(6, "spada");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        morto = new javax.swing.JLabel();
        teschio2 = new javax.swing.JLabel();
        luogo = new javax.swing.JLabel();
        north = new javax.swing.JButton();
        indietro = new javax.swing.JButton();
        trollkey = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        teschio1 = new javax.swing.JLabel();
        orco1 = new javax.swing.JButton();
        orco2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setFont(new java.awt.Font("Papyrus", 3, 18)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setOpaque(true);
        text.setPreferredSize(new java.awt.Dimension(1080, 40));
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1080, -1));

        morto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DEAD.jpg"))); // NOI18N
        morto.setText("jLabel2");
        getContentPane().add(morto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        teschio2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skull2.png"))); // NOI18N
        getContentPane().add(teschio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));

        luogo.setBackground(new java.awt.Color(0, 0, 0));
        luogo.setFont(new java.awt.Font("Papyrus", 3, 24)); // NOI18N
        luogo.setForeground(new java.awt.Color(255, 255, 255));
        luogo.setOpaque(true);
        getContentPane().add(luogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        north.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NORD.png"))); // NOI18N
        north.setBorderPainted(false);
        north.setContentAreaFilled(false);
        north.setFocusPainted(false);
        north.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                northActionPerformed(evt);
            }
        });
        getContentPane().add(north, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 110, 120));

        indietro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHIUSO.png"))); // NOI18N
        indietro.setBorderPainted(false);
        indietro.setContentAreaFilled(false);
        indietro.setFocusPainted(false);
        indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroActionPerformed(evt);
            }
        });
        getContentPane().add(indietro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        trollkey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trollkey.png"))); // NOI18N
        trollkey.setBorderPainted(false);
        trollkey.setContentAreaFilled(false);
        trollkey.setFocusPainted(false);
        trollkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trollkeyActionPerformed(evt);
            }
        });
        getContentPane().add(trollkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, 140));

        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        inventario.setBorderPainted(false);
        inventario.setContentAreaFilled(false);
        inventario.setFocusPainted(false);
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, -1));

        teschio1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/skull.png"))); // NOI18N
        getContentPane().add(teschio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        orco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troll3.png"))); // NOI18N
        orco1.setBorderPainted(false);
        orco1.setContentAreaFilled(false);
        orco1.setFocusPainted(false);
        orco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orco1ActionPerformed(evt);
            }
        });
        getContentPane().add(orco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 30, 590, 690));

        orco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troll2.png"))); // NOI18N
        orco2.setBorderPainted(false);
        orco2.setContentAreaFilled(false);
        orco2.setFocusPainted(false);
        orco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orco2ActionPerformed(evt);
            }
        });
        getContentPane().add(orco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 470, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/troll.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        openInventory();
    }//GEN-LAST:event_inventarioActionPerformed

    private void orco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orco1ActionPerformed
        if (findObject(spada) >= 0) {
            orco1.setVisible(false);
            teschio1.setVisible(true);
            kills++;

        } else {

            text.setText("SEI MORTO,IL TROLL E' TROPPO FORTE!");
            morto.setVisible(true);
            Timer timer = new Timer(6000, event -> {
                this.dispose();
            });
            timer.setRepeats(false);
            timer.start();

        }

    }//GEN-LAST:event_orco1ActionPerformed

    private void trollkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trollkeyActionPerformed
        PickObject(chiavetroll);
        text.setText("Hai raccolto la chiave  di nascosto sfruttando la tua piccolezza!");
        Timer timer = new Timer(3000, event -> {
            text.setText("");
        });
        timer.setRepeats(false);
        timer.start();

    }//GEN-LAST:event_trollkeyActionPerformed

    private void indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroActionPerformed
        goSouth(this);
    }//GEN-LAST:event_indietroActionPerformed

    private void orco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orco2ActionPerformed
        if (findObject(spada) >= 0) {
            orco2.setVisible(false);
            teschio2.setVisible(true);
            kills++;
        } else {

            text.setText("SEI MORTO IL TROLL E' TROPPO FORTE");
            morto.setVisible(true);
            Timer timer = new Timer(6000, event -> {
                this.dispose();
            });
            timer.setRepeats(false);
            timer.start();

        }
    }//GEN-LAST:event_orco2ActionPerformed

    private void northActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_northActionPerformed

        if (kills >= 2) {

            goNorth(this);

        } else {
            text.setText("Ci sono nemici nelle vicinanze che ti sbarrano la strada");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }

    }//GEN-LAST:event_northActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton indietro;
    private javax.swing.JButton inventario;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel luogo;
    private javax.swing.JLabel morto;
    private javax.swing.JButton north;
    private javax.swing.JButton orco1;
    private javax.swing.JButton orco2;
    private javax.swing.JLabel teschio1;
    private javax.swing.JLabel teschio2;
    private javax.swing.JLabel text;
    private javax.swing.JButton trollkey;
    // End of variables declaration//GEN-END:variables
}
