/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progetto;

import static com.mycompany.progetto.Commands.*;
import static com.mycompany.progetto.Inventory.findObject;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.List;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/**
 *
 * @author MSIGaming
 */
public class Room27 extends javax.swing.JFrame {

    /**
     * Creates new form Room27
     */
    int ringactive = 0;
    ProjectObject arsword,thiskey3,thisring;

    public Room27() {
        initComponents();
        arsword = new ProjectObject(10, "spada aragorn");
        thiskey3 = new ProjectObject(9, "chiaveMiddle", "/images/mordorkey.jpg", key3, this);
        thisring = new ProjectObject(2, "anello", "/images/ring.png", ring, this);
        this.addWindowListener(l);
    }
    WindowListener l = new WindowListener() {
        @Override
        public void windowOpened(WindowEvent arg0) {
            text.setText("BALROG:'AAAAAAAARRRHGGGHHHHHHHH!!!");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }

        @Override
        public void windowClosing(WindowEvent arg0) {

        }

        @Override
        public void windowClosed(WindowEvent arg0) {
        }

        @Override
        public void windowIconified(WindowEvent arg0) {

        }

        @Override
        public void windowDeiconified(WindowEvent arg0) {
        }

        @Override
        public void windowActivated(WindowEvent arg0) {
        }

        @Override
        public void windowDeactivated(WindowEvent arg0) {
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        inventory = new javax.swing.JButton();
        west = new javax.swing.JButton();
        ring = new javax.swing.JButton();
        balrogheart = new javax.swing.JButton();
        balrogbody = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        key3 = new javax.swing.JButton();
        balrogfree = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBackground(new java.awt.Color(0, 0, 0));
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setOpaque(true);
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1080, 40));

        inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventario.png"))); // NOI18N
        inventory.setBorderPainted(false);
        inventory.setContentAreaFilled(false);
        inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryActionPerformed(evt);
            }
        });
        getContentPane().add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        west.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CHIUSO.png"))); // NOI18N
        west.setBorderPainted(false);
        west.setContentAreaFilled(false);
        west.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                westActionPerformed(evt);
            }
        });
        getContentPane().add(west, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, -1, -1));

        ring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ring.png"))); // NOI18N
        ring.setBorderPainted(false);
        ring.setContentAreaFilled(false);
        ring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ringActionPerformed(evt);
            }
        });
        getContentPane().add(ring, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 60, 50));

        balrogheart.setBorderPainted(false);
        balrogheart.setContentAreaFilled(false);
        balrogheart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balrogheartActionPerformed(evt);
            }
        });
        getContentPane().add(balrogheart, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 70, 90));

        balrogbody.setBorderPainted(false);
        balrogbody.setContentAreaFilled(false);
        balrogbody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balrogbodyActionPerformed(evt);
            }
        });
        getContentPane().add(balrogbody, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 580, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/balrog.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        key3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/morodor.png"))); // NOI18N
        key3.setBorderPainted(false);
        key3.setContentAreaFilled(false);
        key3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key3ActionPerformed(evt);
            }
        });
        getContentPane().add(key3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 60, 60));

        balrogfree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sfondobarlog.jpg"))); // NOI18N
        getContentPane().add(balrogfree, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryActionPerformed
        // TODO add your handling code here:
        openInventory();
    }//GEN-LAST:event_inventoryActionPerformed

    private void ringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ringActionPerformed
        // TODO add your handling code here:
        ringactive = 1;
        ring.setVisible(false);
        text.setText("Hai attivato l'anello ed ora sei invisibile!Adesso hai un gran vantaggio ma dovrai colpirlo nei punti giusti...");
        Timer timer = new Timer(3000, event -> {
            text.setText("");
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_ringActionPerformed

    private void key3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key3ActionPerformed
        // TODO add your handling code here:
        PickObject(thiskey3);
        text.setText("Ecco l'ultima chiave!!!Prova a tornare a quella porta...");
        Timer timer = new Timer(3000, event -> {
            text.setText("");
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_key3ActionPerformed

    private void balrogbodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balrogbodyActionPerformed
        // TODO add your handling code here:
        if (ringactive == 1) {
            text.setText("La tua spada è potente,ma non abbastanza da scalfire la sua pelle...Trova un punto debole!");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        } else {
            text.setText("In uno scontro alla pari ti farai solo schiacciare!!!Usa ciò che hai a disposizione...");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_balrogbodyActionPerformed

    private void balrogheartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balrogheartActionPerformed
        // TODO add your handling code here:
        if (ringactive == 1) {
            if (findObject(arsword) >= 0) {
                SwingWorker<Void, String> worker = new SwingWorker<Void, String>() {

                @Override
                protected Void doInBackground() throws Exception {
                    this.publish("BALROG:'AAAAAAAARRRRRGGGGGGGHHHHH...ARGH...AAA...A...");
                    Thread.sleep(3000);
                    this.publish("Sei riuscito a sopraffare il demone BALROG!!!");
                    Thread.sleep(3000);
                    this.publish("");
                    jLabel1.setVisible(false);
                    balrogheart.setVisible(false);
                    balrogbody.setVisible(false);
                    return null;
                }

                @Override
                protected void process(List<String> res) {
                    for (String thistext : res) {
                        text.setText(thistext);
                    }
                }

            };

            worker.execute();
            } else {
                text.setText("Hai trovato il punto critico,ma ti serve una spada potente per sopraffarlo!!!");
                Timer timer = new Timer(3000, event -> {
                    text.setText("");
                });
                timer.setRepeats(false);
                timer.start();
            }
        } else {
            text.setText("In uno scontro alla pari ti farai solo schiacciare!!!Usa ciò che hai a disposizione...");
            Timer timer = new Timer(3000, event -> {
                text.setText("");
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_balrogheartActionPerformed

    private void westActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_westActionPerformed
        // TODO add your handling code here:
        goWest(this);
    }//GEN-LAST:event_westActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room27.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room27().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balrogbody;
    public javax.swing.JLabel balrogfree;
    private javax.swing.JButton balrogheart;
    private javax.swing.JButton inventory;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JButton key3;
    private javax.swing.JButton ring;
    private javax.swing.JLabel text;
    private javax.swing.JButton west;
    // End of variables declaration//GEN-END:variables
}
